package petr.telecardreader;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;

public class ConfigFile extends File {

	static String fileSeparator = System.getProperty("file.separator");
	static String configFileName = System.getProperty("user.home")
			+ fileSeparator + ".telecardreader" + fileSeparator
			+ "telecardreader.conf";

	String fileName;
	String newline = "\n";

	Properties properties = new Properties();

	public ConfigFile(String parFileName) {

		super(parFileName);
		this.fileName = parFileName;
		loadProperties();

	}

	public ConfigFile() {

		super(configFileName);
		this.fileName = configFileName;
		loadProperties();

	}

	public void loadProperties() {

		FileReader readConfig = null;
		BufferedReader rc = null;
		Boolean notFound = false;

		if (this.exists() == true) {
			try {
				readConfig = new FileReader(this);
				rc = new BufferedReader(readConfig);
			} catch (FileNotFoundException e) {
				TelecardReader.recError(new ErrorRecord(
						"Konfigurační soubor nebyl nalezen." + newline + "("
								+ getAbsolutePath() + ")", -3));
				notFound = true;
			}
		} else {
			TelecardReader.recError(new ErrorRecord(
					"Konfigurační soubor nebyl nalezen." + newline + "("
							+ this.getAbsolutePath() + ")", -3));
			notFound = true;
		}

		if (!notFound) {
			try {
				properties.load(rc);
			} catch (IOException e) {
				TelecardReader.recError(new ErrorRecord(
						"Chyba během čtení konfiguračního souboru." + newline
								+ "(" + this.getAbsolutePath() + ")", -4));
			}

			try {
				rc.close();
				readConfig.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

	public void saveProperties() {

		FileWriter writeConfig = null;
		BufferedWriter wc = null;
		String warning = "#######################################################"
				+ newline
				+ "# Do not edit this file. It's automatically generated! #"
				+ newline
				+ "########################################################";

		try {
			writeConfig = new FileWriter(this);
			wc = new BufferedWriter(writeConfig);
			properties.store(wc, warning);
			wc.close();
			writeConfig.close();
			TelecardReader.setStatus("Nastavení bylo uloženo.");
		} catch (IOException e) {
			TelecardReader.recError(new ErrorRecord(
					"Chyba během zápisu do konfiguračního souboru." + newline
							+ "(" + this.getAbsolutePath() + ")", -5));
		}

	}

	public String getPropertyValue(String key) {

		return properties.getProperty(key) == null ? "" : properties
				.getProperty(key);

	}

	public void setPropertyValue(String key, String value) {

		properties.setProperty(key, value);

	}

}
